//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zuki.hdhomeruntray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Broadcast")]
        public global::zuki.hdhomeruntray.discovery.DiscoveryMethod DiscoveryMethod {
            get {
                return ((global::zuki.hdhomeruntray.discovery.DiscoveryMethod)(this["DiscoveryMethod"]));
            }
            set {
                this["DiscoveryMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TwoMinutes")]
        public global::zuki.hdhomeruntray.DiscoveryInterval DiscoveryInterval {
            get {
                return ((global::zuki.hdhomeruntray.DiscoveryInterval)(this["DiscoveryInterval"]));
            }
            set {
                this["DiscoveryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public global::zuki.hdhomeruntray.EnabledDisabled StartAutomatically {
            get {
                return ((global::zuki.hdhomeruntray.EnabledDisabled)(this["StartAutomatically"]));
            }
            set {
                this["StartAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enabled")]
        public global::zuki.hdhomeruntray.EnabledDisabled HoverActions {
            get {
                return ((global::zuki.hdhomeruntray.EnabledDisabled)(this["HoverActions"]));
            }
            set {
                this["HoverActions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public global::zuki.hdhomeruntray.EnabledDisabled UnpinAutomatically {
            get {
                return ((global::zuki.hdhomeruntray.EnabledDisabled)(this["UnpinAutomatically"]));
            }
            set {
                this["UnpinAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System")]
        public global::zuki.hdhomeruntray.Theme Theme {
            get {
                return ((global::zuki.hdhomeruntray.Theme)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System")]
        public global::zuki.hdhomeruntray.VirtualLEDColorSet VirtualLEDColorSet {
            get {
                return ((global::zuki.hdhomeruntray.VirtualLEDColorSet)(this["VirtualLEDColorSet"]));
            }
            set {
                this["VirtualLEDColorSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System")]
        public global::zuki.hdhomeruntray.HoverActionsDelay HoverActionsDelay {
            get {
                return ((global::zuki.hdhomeruntray.HoverActionsDelay)(this["HoverActionsDelay"]));
            }
            set {
                this["HoverActionsDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public global::zuki.hdhomeruntray.EnabledDisabled ShowTunerTools {
            get {
                return ((global::zuki.hdhomeruntray.EnabledDisabled)(this["ShowTunerTools"]));
            }
            set {
                this["ShowTunerTools"] = value;
            }
        }
    }
}
