//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zuki.hdhomeruntray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Broadcast")]
        public global::zuki.hdhomeruntray.discovery.DiscoveryMethod DiscoveryMethod {
            get {
                return ((global::zuki.hdhomeruntray.discovery.DiscoveryMethod)(this["DiscoveryMethod"]));
            }
            set {
                this["DiscoveryMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TwoMinutes")]
        public global::zuki.hdhomeruntray.DiscoveryInterval DiscoveryInterval {
            get {
                return ((global::zuki.hdhomeruntray.DiscoveryInterval)(this["DiscoveryInterval"]));
            }
            set {
                this["DiscoveryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SystemDefault")]
        public global::zuki.hdhomeruntray.TrayIconHoverDelay TrayIconHoverDelay {
            get {
                return ((global::zuki.hdhomeruntray.TrayIconHoverDelay)(this["TrayIconHoverDelay"]));
            }
            set {
                this["TrayIconHoverDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::zuki.hdhomeruntray.TunerStatusColorSource TunerStatusColorSource {
            get {
                return ((global::zuki.hdhomeruntray.TunerStatusColorSource)(this["TunerStatusColorSource"]));
            }
            set {
                this["TunerStatusColorSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public global::zuki.hdhomeruntray.EnabledDisabled AutoStart {
            get {
                return ((global::zuki.hdhomeruntray.EnabledDisabled)(this["AutoStart"]));
            }
            set {
                this["AutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enabled")]
        public global::zuki.hdhomeruntray.EnabledDisabled TrayIconHover {
            get {
                return ((global::zuki.hdhomeruntray.EnabledDisabled)(this["TrayIconHover"]));
            }
            set {
                this["TrayIconHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Disabled")]
        public global::zuki.hdhomeruntray.EnabledDisabled AutoUnpin {
            get {
                return ((global::zuki.hdhomeruntray.EnabledDisabled)(this["AutoUnpin"]));
            }
            set {
                this["AutoUnpin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System")]
        public global::zuki.hdhomeruntray.Theme AppTheme {
            get {
                return ((global::zuki.hdhomeruntray.Theme)(this["AppTheme"]));
            }
            set {
                this["AppTheme"] = value;
            }
        }
    }
}
